apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
resources:
  - ./gotk-components.yaml
  - ./gotk-sync.yaml
  - ../namespaces/podinfo-test.yaml
  - ../apps/podinfo.yaml
  - ../apps/jenkins.yaml
  - ../common/nginx.yaml
